internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from shop.views import (
    base_view,
    category_view,
    product_view,
    cart_view,
    add_to_cart_view,
    remove_from_cart_view,
    change_item_qty,
    checkout_view,
    order_create_view,
    make_order_view,
    account_view,
    registration_view,
    login_view,
    support_view,
    send_support_view,
)

urlpatterns = [
    path('category/<category_slug>/', category_view, name='category_detail'),
    path('product/<product_slug>/', product_view, name='product_detail'),
    path('add_to_cart/',add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/', remove_from_cart_view, name='remove_from_cart'),
    path('change_item_qty', change_item_qty, name='change_item_qty'),
    path('cart/',cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('thank_you/', make_order_view, name='thank_you'),
    path('order/', order_create_view, name='create_order'),
    path('account/', account_view, name='account'),
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),
    path('support/', support_view, name='support'),
    path('suppor_sended/', send_support_view, name='support_sended'),
    path('', base_view, name='base'),
]

shop/models.py
from __future__ import unicode_literals
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.urls import reverse
from transliterate import translit
from decimal import Decimal
from django.conf import settings
from djongo import models as mdl


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class Category(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return u'%s' % (self.name)

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


class Brand(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_category_slug, sender=Category)


class ProductManager(models.Manager):

    def all(self):
        return super(ProductManager, self).get_queryset().filter(available=True, quantity__gt=0)


class Product(models.Model):

    category = models.ForeignKey(Category,null=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(Brand, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True)
    description = models.TextField()
    processor = models.DecimalField(max_digits=9, decimal_places=2, blank=True, default=0)
    ozu = models.DecimalField(max_digits=9, decimal_places=2, blank=True, default=0)
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    predicted_price = models.DecimalField(max_digits=9, decimal_places=2, blank=True, default=0)
    quantity = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
        return u'%s' % (self.title)

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


def pre_save_product_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(str(instance.title))
        instance.slug = slug


pre_save.connect(pre_save_product_slug, sender=Product)


class CartItem(models.Model):

    product = models.ForeignKey(Product,null=True, on_delete=models.SET_NULL)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2,default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)


class Cart(models.Model):

    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()

    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()


ORDER_STATUS_CHOICES = (
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполняется', 'Выполняется'),
    ('Оплачен', 'Оплачен')
)


class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    items = models.ForeignKey(Cart, null=True, on_delete=models.SET_NULL)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255, blank=True)
    buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')), default='Самовывоз')
    data = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(blank=True)
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return "Заказ №{0}".format(self.id)


class Comment(mdl.Model):

    created_at = mdl.DateTimeField(auto_now_add=True, auto_now=False)

    name = mdl.CharField(max_length=20, null=True)
    comment = mdl.TextField(max_length=1000, null=True)

    def __str__(self):
        return "{0} - {1}".format(self.name, self.created_at)

shop/views.py
from django.shortcuts import render
from shop.models import Category, Product, CartItem, Cart, Order, Comment
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from decimal import Decimal
from shop.forms import OrderForm, RegistrationForm, LoginForm, CommentForm
from django.contrib.auth import login, authenticate
from sklearn.linear_model import LinearRegression


def base_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products,
        'cart': cart,
    }
    return render(request, 'base.html', context)


def product_view(request, product_slug):

    x = []
    y = []
    for product in Product.objects.all():
        x.append([product.processor, product.ozu])
        y.append(product.price)
    model = LinearRegression().fit(x, y)

    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)

    product.predicted_price = model.predict([[product.processor, product.ozu]])

    categories = Category.objects.all()

    context = {
        'product': product,
        'categories':categories,
        'cart': cart
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    category = Category.objects.get(slug=category_slug)
    products_of_category = Product.objects.filter(category=category)
    categories = Category.objects.all()
    context = {
        'category': category,
        'products_of_category': products_of_category,
        'categories': categories,
        'cart': cart
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'cart.html', context)


def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    product.quantity -= 1
    product.save()
    return JsonResponse({
        'cart_total': cart.items.count(),
        'cart_total_price': cart.cart_total
    })


def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    product.quantity += 1
    product.save()
    return JsonResponse({
        'cart_total':cart.items.count(),
        'cart_total_price': cart.cart_total
    })


def change_item_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart_item.qty = int(qty)
    cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
    cart_item.save()
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({
        'cart_total': cart.items.count(),
        'item_total': cart_item.item_total,
        'cart_total_price': cart.cart_total
    })


def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories,
    }
    return render(request, 'checkout.html', context)


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    form = OrderForm(request.POST or None)
    context = {
        'form': form,
        'cart': cart,
        'categories': categories,
    }
    return render(request, 'order.html', context)


def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']

        new_order = Order.objects.create(
            user=request.user,
            items=cart,
            total=cart.cart_total,
            first_name=name,
            last_name=last_name,
            phone=phone,
            buying_type=buying_type,
            address=address,
            comments=comments
        )

        del request.session['cart_id']
        del request.session['total']
        return render(request, 'thank_you.html')
    return render(request, 'order.html', {'categories': categories})


def account_view(request):

    categories = Category.objects.all()
    order = Order.objects.filter(user=request.user).order_by('-id')
    orders = Order.objects.order_by('-id')
    total_price = 0
    for e in orders:
        total_price += e.total
    context = {
        'order': order,
        'categories': categories,
        'orders': orders,
        'total_price': total_price,
    }
    return render(request, 'account.html', context)


def registration_view(request):

    categories = Category.objects.all()
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']

        new_user.username = username
        new_user.set_password(password)
        new_user.email = email
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()

        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'categories': categories,
        'form': form,
    }
    return render(request, 'registration.html', context)


def login_view(request):

    categories = Category.objects.all()
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'categories': categories,

shop/templates/account.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.username == 'admin' %}
        <br>
        <h4 class="text-center">Все заказы</h4>
        <br>
            <table class="table">
        <tr style="background: lightgrey">
            <td class="text-center">Номер заказа</td>
            <td class="text-center">Дата заказа</td>
            <td class="text-center">Статус заказа</td>
            <td class="text-center">Стоимость заказа</td>
            <td class="text-center">Детали заказа</td>
            </tr>
    {% for item in orders %}
            <tr>
            <td class="text-center">{{ item.id }}</td>
            <td class="text-center">{{ item.data }}</td>
            <td class="text-center">{{ item.status }}</td>
            <td class="text-center">{{ item.total }} б.р.</td>
            <td class="text-center"><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}">
  Детали заказа
</button></td>
            </tr>
    {% endfor %}
     <tr>
        <td></td>
        <td></td>
         <td class="text-center"><strong>Стоимость всех заказов</strong></td>
         <td class="text-center"><strong>{{ total_price }} б.р.</strong></td>
        <td></td>
    </tr>
    </table>
    {% else %}
        <h3 class="text-center">Личный кабинет пользователя {{ request.user }}</h3>
<br>
<h4 class="text-center">Ваши заказы</h4>
    <table class="table">
        <tr style="background: lightgrey">
            <td class="text-center">Номер заказа</td>
            <td class="text-center">Дата заказа</td>
            <td class="text-center">Статус заказа</td>
            <td class="text-center">Стоимость заказа</td>
            <td class="text-center">Детали заказа</td>
            </tr>
    {% for item in order %}
            <tr>
            <td class="text-center">{{ item.id }}</td>
            <td class="text-center">{{ item.data }}</td>
            <td class="text-center">{{ item.status }}</td>
            <td class="text-center">{{ item.total }} б.р.</td>
            <td class="text-center"><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}">
  Детали заказа
</button></td>
            </tr>
    {% endfor %}
    </table>
    {% endif %}
{% if request.user.username == 'admin' %}
    {% for item in orders %}
<div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Заказ №{{ item.id }}</h4>
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
      <h3>Товар</h3>
        <table class="table">
            {% for order_item in item.items.items.all %}
            <tr>
                <td>{{ order_item.product.title }}</td>
                <td>{{ order_item.qty }} шт.</td>
                <td>{{ order_item.item_total }} б.р.</td>
            </tr>
                {% endfor %}
            <tr>
                    <td></td>
                    <td>Итого:</td>
                    <td><strong>{{ item.items.cart_total }} б.р.</strong></td>
                </tr>
        </table>
      <h3>Заказчик</h3>
      <p>Имя: {{ item.first_name }}</p>
      <p>Фамилия: {{ item.last_name }}</p>
      <p>Телефон: {{ item.phone }}</p>
      <h3>Тип доставки</h3>
      <p>{% if item.buying_type == 'self' %}Самовывоз{% else %}Доставка{% endif %}</p>
      <p>{% if item.buying_type == 'delivery' %}{{ item.address }}{% endif %}</p>
      <h3>Комментарий к заказу</h3>
      <p>{{ item.comments }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
    {% endfor %}
    {% else %}
    {% for item in order %}
        <div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Заказ №{{ item.id }}</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <table class="table">
            {% for order_item in item.items.items.all %}
            <tr>
                <td>{{ order_item.product.title }}</td>
                <td>{{ order_item.qty }} шт.</td>
                <td>{{ order_item.item_total }} б.р.</td>
            </tr>
                {% endfor %}
            <tr>
                    <td></td>
                    <td>Итого:</td>
                    <td><strong>{{ item.items.cart_total }} б.р.</strong></td>
                </tr>
        </table>
      <h3>Заказчик</h3>
      <p>Имя: {{ item.first_name }}</p>
      <p>Фамилия: {{ item.last_name }}</p>
      <p>Телефон: {{ item.phone }}</p>
      <h3>Тип доставки</h3>
      <p>{% if item.buying_type == 'self' %}Самовывоз{% else %}Доставка{% endif %}</p>
      <p>{% if item.buying_type == 'delivery' %}{{ item.address }}{% endif %}</p>
      <h3>Комментарий к заказу</h3>
      <p>{{ item.comments }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
    {% endfor %}
    {% endif %}
{% endblock %}

shop/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <hr>
    {% if cart.items.count > 0 %}
            <h3 class="text-center">Ваша корзина</h3>
    <hr>
<div class="my-cart">
<table class="table">
<tr>
    <td class="text-center"><strong>Товар</strong></td>
    <td class="text-center"><strong>Количество</strong></td>
    <td class="text-center"><strong>Цена</strong></td>
    <td class="text-center"></td>
</tr>
{% for item in cart.items.all %}
    <tr class="cart-item-{{ item.product.id }}">
        <td class="text-center">{{ item.product.title }}</td>
    <td class="text-center">
        <form action="" method="GET">
            <input type="number" name="qty" class="cart-item-qty" data-id="{{ item.id }}" value="{{ item.qty }}" min="1" style="width: 50px">
        </form>
    </td>
    <td class="text-center" id="cart-item-total-{{ item.id }}">{{ item.item_total }} б.р. </td>
    <td class="text-center"><a href="#" class="remove_from_cart" data-slug="{{ item.product.slug }}" data-id="{{ item.product.id }}"><button class="btn btn-primary">Удалить из корзины</button></a></td>
    </tr>
{% endfor %}
<tr>
    <td></td>
    <td class="text-center"><strong>Итого: </strong></td>
    <td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} б.р.</strong></td>
    <td></td>
</tr>
</table>
<br>
<p class="text-right"><a href="{% url 'checkout' %}"><button class="btn btn-primary">Предварительный заказ</button></a></p>
</div>
        <h3 class="cart-empty"></h3>
    {% else %}
            <h3 class="text-center">Ваша корзина пуста</h3>
        <p style="text-align: center"><img src="http://tomasplus.com.ua/assets/template/images/cart-empty.png" alt=""></p>
    {% endif %}
    <script src='{% static "js/jquery.min.js" %}'></script>
    <script>
        $(document).ready(function () {
            $('.cart-empty').css('display', 'none')
            $('.remove_from_cart').on('click', function(e) {
                e.preventDefault()
                product_slug = $(this).attr('data-slug')
                item_product_id = $(this).attr('data-id')
                data = {
                    product_slug: product_slug
                }
                $.ajax({
                    type: "GET",
                    url: '{% url "remove_from_cart" %}',
                    data: data,
                    success: function (data) {
                        $('#cart_count').html(data.cart_total)
                        $('.cart-item-'+item_product_id).css('display', 'none')
                        $('#cart-total-price').html('<strong>'+ parseFloat(data.cart_total_price).toFixed(2)+ ' б.р.</strong>' )
                        if(parseInt(data.cart_total) == 0){
                            $('.my-cart').css('display', 'none')
                            $('.cart-empty').css('display', 'block')
                            $('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3><p style="text-align: center"><img src="http://tomasplus.com.ua/assets/template/images/cart-empty.png" alt=""></p>')
                        }
                    }
                })
            })
        })
    $(document).ready(function () {
        $('.cart-item-qty').on('click', function () {
            qty = $(this).val()
            item_id = $(this).attr('data-id')
            data = {
                qty: qty,
                item_id: item_id
            }
            $.ajax({
                type: "GET",
                url:'{% url "change_item_qty" %}',
                data: data,
                success: function (data) {
                    $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2)+ ' б.р.')
                    $('#cart-total-price').html('<strong>'+ parseFloat(data.cart_total_price).toFixed(2)+ ' б.р.</strong>' )
                }
            })
        })
    })
    </script>
{% endblock content %}

shop/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2>{{ category.name }}</h2>
        <div class="row">
          {% for product in products_of_category %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt="" style="width: 80%; height: 300px;"></a>
              <div class="card-body">
                <h4 class="card-title">
                 <p class="text-center"> <a href="{{ product.get_absolute_url }}">{{ product.title }}</a></p>
                </h4>
                <h5 class="text-center">{{ product.price }} б.р.</h5>
                  {% if request.user.is_authenticated %}
                  <p class="text-center"><a href="#" class="add_to_cart" data-slug="{{ product.slug }}" ><button class="btn btn-primary center-block">Добавить в корзину</button> </a></p>
                  {% else %}
                  {% endif %}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
    <script src='{% static "js/jquery.min.js" %}'></script>
        <script>
        $(document).ready(function () {
            $('.add_to_cart').on('click', function(e) {
                e.preventDefault()
                product_slug = $(this).attr('data-slug')
                data = {
                    product_slug: product_slug
                }
                $.ajax({
                    type: "GET",
                    url: '{% url "add_to_cart" %}',
                    data: data,
                    success: function (data) {
                        $('#cart_count').html(data.cart_total)
                    }
                })
            })
        })
    </script>
{% endblock content %}

shop/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <br>
<h3 class="text-center">Авторизация</h3>
    <br>
    <form action="" method="POST">
    {% csrf_token %}
        {{ form|crispy }}
    <input type="submit" class="btn btn-success btn-block" value="Войти">
    </form>
{% endblock %}

shop/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<br><br>
<form action="{% url 'thank_you'%}" method="POST">
{% csrf_token %}
<div class="row">
    <div class="col-md-4">
        {{ form.name|as_crispy_field }}
    </div>
    <div class="col-md-4">
        {{ form.last_name|as_crispy_field }}
    </div>
    <div class="col-md-4">
        {{ form.phone|as_crispy_field }}
    </div>
</div>
{{ form.buying_type|as_crispy_field }}
{{ form.address|as_crispy_field }}
{{ form.date|as_crispy_field }}
{{ form.comments|as_crispy_field }}
<input type="submit" class="btn btn-primary" value="Оформить заказ" >
</form>
<script src='{% static "js/jquery.min.js" %}'></script>
    <script>
        $(document).ready(function () {
            $('#div_id_address').css('display', 'none')
            $('#id_buying_type').on('click', function () {
                buying_type = $(this).val()
                if(buying_type == 'delivery'){
                    $('#div_id_address').css('display', 'block')
                }else{
                    $('#div_id_address').css('display', 'none')
                }
            })
            $('#id_date_month').css('width', '140px')
            $('#id_date_day').css('width', '80px')
            $('#id_date_year').css('width', '100px')
            $('#id_date_month').css('display', 'inline')
            $('#id_date_day').css('display', 'inline')
            $('#id_date_year').css('display', 'inline')
        })
    </script>
{% endblock content %}